myproject/core/urls.py
from django.urls import path
from myproject.core import views as c

app_name = 'core'

urlpatterns = [
    path('', c.home, name='home'),
    path('person/', c.PersonList.as_view(), name='person_list'),
    path('person/add/', c.person_create, name='person_add'),
    path('person/phone/add/', c.person_phone_create, name='person_phone_create'),
    path('person/<int:pk>/', c.person_detail, name='person_detail'),
    path('person/<int:pk>/phones/', c.person_phones, name='person_phones'),
    path('person/<int:pk>/edit/', c.person_update, name='person_edit'),
    path('person/<int:pk>/delete/', c.person_delete, name='person_delete'),
]

myproject/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from localflavor.br.br_states import STATE_CHOICES

PHONE_TYPE = (
    ('pri', 'principal'),
    ('com', 'comercial'),
    ('res', 'residencial'),
    ('cel', 'celular'),
    ('cl', 'Claro'),
    ('oi', 'Oi'),
    ('t', 'Tim'),
    ('v', 'Vivo'),
    ('n', 'Nextel'),
    ('fax', 'fax'),
    ('o', 'outros'),
)


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(u'endereço', max_length=100, blank=True)
    complement = models.CharField('complemento', max_length=100, blank=True)
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField(
        'UF',
        max_length=2,
        choices=STATE_CHOICES,
        blank=True
    )
    cep = models.CharField('CEP', max_length=9, blank=True)

    class Meta:
        abstract = True


class Person(TimeStampedModel, Address):
    first_name = models.CharField('nome', max_length=50)
    last_name = models.CharField(
        'sobrenome',
        max_length=50,
        null=True,
        blank=True
    )
    email = models.EmailField(null=True, blank=True)
    blocked = models.BooleanField('bloqueado', default=False)

    class Meta:
        ordering = ['first_name']
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'

    def __str__(self):
        return ' '.join(filter(None, [self.first_name, self.last_name]))

    full_name = property(__str__)

    def get_absolute_url(self):
        return r('core:person_detail', pk=self.pk)


class Phone(models.Model):
    phone = models.CharField('telefone', max_length=20, blank=True)
    person = models.ForeignKey('Person', on_delete=models.CASCADE)
    phone_type = models.CharField(
        'tipo',
        max_length=3,
        choices=PHONE_TYPE,
        default='pri'
    )

    def __str__(self):
        return self.phone

myproject/core/forms.py
from django import forms
from .models import Person


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email']

myproject/core/views.py
import json
from django.core import serializers
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy as r
from django.views.generic import ListView, DetailView
from django.views.generic import UpdateView, DeleteView
from .mixins import NameSearchMixin
from .models import Person, Phone
from .forms import PersonForm


def home(request):
    return render(request, 'index.html')


class PersonList(NameSearchMixin, ListView):
    model = Person
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(PersonList, self).get_context_data(**kwargs)
        context['form'] = PersonForm()
        return context


person_detail = DetailView.as_view(model=Person)


def person_create(request):
    if request.method == 'POST':
        if request.is_ajax():
            form = PersonForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponse('OK')
            else:
                return HttpResponse(status=400)
        else:
            return render(request, 'core/person_form.html', {'form': PersonForm(request.POST)})
    return render(request, 'core/person_form.html', {'form': PersonForm()})


person_update = UpdateView.as_view(model=Person, form_class=PersonForm)

person_delete = DeleteView.as_view(
    model=Person,
    success_url=r('core:person_list')
)


def person_phones(request, pk):
    phones = Phone.objects.filter(person=pk)
    data = serializers.serialize('json', phones)
    return HttpResponse(data, content_type='application/json')


def person_phone_create(request):
    if request.method == 'POST':
        person_pk = request.POST['person']
        person = Person.objects.get(pk=person_pk)
        phone = request.POST['phone']
        Phone.objects.create(person=person, phone=phone)
        data = phone
    return HttpResponse(data, content_type='application/json')

myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Django boilerplate">
  <meta name="author" content="rg3915">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">

  <title>
    {% block title %}Django{% endblock title %}
  </title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <link rel="stylesheet" href="{% static "css/social.css" %}">
  <!-- Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <!-- VueJS -->
  <script src="https://unpkg.com/vue"></script>
  <!-- axios -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>


  <style type="text/css">
    body {
      padding-top: 50px;
      /*color: #5a5a5a;*/
    }
  </style>

</head>
<body>
  {% include "nav.html" %}
  <div id="wrap">
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </div>
  {% include "footer.html" %}

  {% block js %}{% endblock js %}
</body>
</html>

myproject/core/templates/core/person_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Person Detail{% endblock title %}

{% block content %}

<style>
  .span-is-link {
    text-decoration: none;
    cursor: pointer;
  }
  .badge{
    display:inline-block;
    padding:.25em .4em;
    /*font-size:75%;*/
    font-weight:700;
    line-height:1;
    text-align:center;
    white-space:nowrap;
    vertical-align:baseline;
    border-radius:.25rem
  }
  .badge-success{
    color:#fff;
    background-color:#4dbd74
  }
  .badge-success[href]:focus,.badge-success[href]:hover{
    color:#fff;
    text-decoration:none;
    background-color:#3a9d5d
  }
</style>

<div id="app" data-pk="{{ person.pk }}">

<ul class="breadcrumb">
  <li><a href="{% url 'core:home' %}">Home</a> <span class="divider"></span></li>
  <li><a href="{% url 'core:person_list' %}">Contatos</a> <span class="divider"></span></li>
  <li class="active">{{ object.full_name }}</li>
</ul>

<div class="col-lg-8">
  <div class="col-md-2 column">
    <img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png" class="img-square" style="height: 100px;" />
  </div>
  <div class="col-md-offset-3 column">
    <h1>{{ object.full_name }}</h1>
    {% if object.email %}
      <h4><span class="glyphicon glyphicon-envelope"></span><a href="#"> {{ object.email }}</a></h4>
    {% endif %}
    <div class="social">
      <ul>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-skype"></i></a></li>
        <li><a href="#"><i class="fa fa-slack"></i></a></li>
      </ul>
    </div>
  </div>

  </br>

  <table class="table table-user-information">
    <tbody>
      <tr>
        <th></th>
        <td>
          <span class="span-is-link badge badge-success" data-target="#phoneModal" data-toggle="modal">
            <i class="fa fa-plus"> Adicionar</i>
          </span>
        </td>
      </tr>
      {% if object.phone_set.all %}
        <tr v-for="phone in phones">
            <th class="col-md-3 text-right"><span class="glyphicon glyphicon-earphone"></span></th>
          <td>${ phone.phone } <i class="fa fa-whatsapp ok"></i></td>
        </tr>
        <!-- { for phone in object.phone_set.all %}
          <tr>
            <th class="col-md-3 text-right"><span class="glyphicon glyphicon-earphone"></span></th>
            <td>{ phone.phone }} <i class="fa fa-whatsapp ok"></i> { phone.get_phone_type_display }}</td>
          </tr>
        { endfor %} -->
      {% else %}
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-earphone"></span></th>
          <td>---</td>
        </tr>
      {% endif %}

      {% if object.address %}
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-map-marker"></span></th>
          <td>{{ object.address }}
            {% if object.complement %} - {{ object.complement }}{% endif %}
            {% if object.district %} - {{ object.district }}{% endif %}
          </td>
        </tr>
        <tr>
          <th class="col-md-3 text-right"></th>
          <td>
            {% if object.city %}{{ object.city }}{% endif %}
            {% if object.uf %} - {{ object.uf }}{% endif %}
            {% if object.cep %} - {{ object.cep }}{% endif %}
          </td>
        </tr>
      {% endif %}
      <tr>
        <th class="col-md-3 text-right">Bloqueado</th>
          <td><span class="glyphicon {{ object.blocked|yesno:'glyphicon-ok-sign ok,glyphicon-minus-sign no'}}"></span></td>
      </tr>

    </tbody>
  </table>
  <!-- edit -->
  <a href="{% url 'core:person_edit' person.pk %}">
      <button id="edit_person" type="button" class="btn btn-success">
          <span class="fa fa-pencil"></span> Editar
      </button>
  </a>
  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
      <span class="fa fa-times"></span> Excluir
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
      </div>
        <form action="{% url 'core:person_delete' person.id %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          Deseja mesmo deletar "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="phoneModal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
        <h4 class="modal-title" id="myModalLabel">
          Adicionar Telefone
        </h4>
      </div>
      <form action="." method="POST">
        <div class="modal-body">
          <div class="form-group">
            {% csrf_token %}
            <label class="control-label" for="id_phone">Telefone</label>
            <input id="id_phone" name="phone" v-model="phone" type="text" class="form-control" maxlength="15" placeholder="(11) 98765-4321" autofocus />
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary" @click="save_phone" data-dismiss="modal">
            Salvar
          </button>
          <button type="button" class="btn btn-default" data-dismiss="modal">
            Fechar
          </button>
        </div>
      </form>
    </div>
  </div>
</div>


</div>

{% endblock content %}

{% block js %}

  <script>
    axios.defaults.xsrfHeaderName = 'X-CSRFToken'
    axios.defaults.xsrfCookieName = 'csrftoken'
    var app = new Vue({
      el: '#app',
      delimiters: ['${', '}'],
      data: {
        person: '',
        phones: [],
        phone: ''
      },
      methods: {
        get_phones(page){
          axios.get('/person/' + page + '/phones/')
          .then((result) => {
            this.phones = result.data.map((item) => {
              return {phone: item.fields.phone, phone_type: item.fields.phone_type}
            })
          })
        },
        save_phone(){
          let bodyFormData = new FormData()
          bodyFormData.append('person', this.person)
          bodyFormData.append('phone', this.phone)
          // let config = {headers: {'Content-Type': 'multipart/form-data'}}
          axios.post('/person/phone/add/', bodyFormData)
          .then((response) => {
            this.phones.push(
              {phone: response.data}
            )
            this.phone = ''
          })
        }
      },
      mounted(){
        this.person = this.$el.getAttribute('data-pk')
        this.get_phones(this.person)
      }
    })
  </script>

{% endblock js %}

myproject/core/templates/core/person_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Person Form{% endblock title %}

{% block content %}

<div class="page-header">
    <h2>Novo Contato</h2>
</div>

<form id="ajaxform" class="form-horizontal" action="{% url 'core:person_add' %}" method="POST">
    {% csrf_token %}
    {{ form.non_fields_errors }}
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.first_name.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.first_name|attr:"class:form-control" }} {{ form.first_name.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.last_name.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.last_name|attr:"class:form-control" }} {{ form.last_name.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.email.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.email|attr:"class:form-control" }} {{ form.email.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.address.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.address|attr:"class:form-control" }} {{ form.address.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.complement.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.complement|attr:"class:form-control" }} {{ form.complement.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.district.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.district|attr:"class:form-control" }} {{ form.district.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.city.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.city|attr:"class:form-control" }} {{ form.city.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.uf.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.uf|attr:"class:form-control" }} {{ form.uf.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.cep.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.cep|attr:"class:form-control" }} {{ form.cep.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.blocked.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.blocked }} {{ form.blocked.errors }}
        </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2 col-sm-offset-2">
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
</form>

<script>
  //callback handler for form submit
  $("#ajaxform").submit(function(e)
  {
      var postData = $(this).serialize();
      var formURL = $(this).attr("action");
      $.ajax(
      {
          url : formURL,
          type: "POST",
          data : postData,
          success:function(data, textStatus, jqXHR) 
          {
              $("#ajaxform").html(data);
          },
          error: function(jqXHR, textStatus, errorThrown) 
          {
              alert('Deu erro!');
          }
      });
      e.preventDefault(); //STOP default action
  });
</script>

{% endblock content %}

myproject/core/templates/core/person_list.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}Contatos{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
    <!-- add -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-person">
      <span class="glyphicon glyphicon-plus"></span> Adicionar
    </button>
    <!-- search form -->
    <div class="form-group">
      <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
      <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<div class="page-header">
<h2><h2><i class="fa fa-user"></i> Lista de Contatos</h2>
</div>

<style>
  .hide-phone{
    display: none;
  }
</style>

<div>
{% if person_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>UF</th>
      </tr>
    </thead>
    <tbody>
    {% for person in person_list %}
      <tr>
        <td><a href="{{ person.get_absolute_url }}">{{ person.full_name }}</a></td>
        <td>{{ person.email }}</td>
        <td><button class='btn btn-default js-phone' data-url="{% url 'core:person_phones' person.pk %}">Phone</button></td>
        {% for p in person.phone_set.all %}
          <td class='hide-phone'>{{ p }}</td>
        {% endfor %}
        <td>{{ person.get_uf_display }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}
</div>

<!-- Modal -->
<div id="modal-person" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form action="">

        <div class="modal-header">
          <button class="close" aria-label="Close" data-dismiss="modal" type="button">
            <span aria-hidden="True">&times;</span>
          </button>
          <h4 class="modal-title">Novo</h4>
        </div> <!-- header -->

        <div class="modal-body">
          {% csrf_token %}
          {{ form|bootstrap }}
        </div> <!-- body -->

        <div class="modal-footer">
          <button type="submit" id="add_person" name="add_person" class="btn btn-primary">Salvar</button>
          <button id="dismiss_person" type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div> <!-- footer -->

      </form>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="phoneModal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
        <h4 class="modal-title" id="myModalLabel">
          Phones
        </h4>
      </div>
      <div class="modal-body">
        <table class="table">
          <tbody id="phoneBody"></tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          Close
        </button>
      </div>
    </div>
  </div>
</div>



<script>
  // callback handler for form submit
  $("#modal-person form").submit(function(e) {
      e.preventDefault(); //STOP default action
      var postData = $(this).serialize();
      var formURL = "{% url 'core:person_add' %}";
      $.ajax(
      {
          url : formURL,
          type: "POST",
          data : postData,
          success:function(data, textStatus, jqXHR) 
          {
              $("#modal-person").modal('hide');
              location.href = '/person/';
          },
          error: function(jqXHR, textStatus, errorThrown) 
          {
              alert('Deu erro!');
          }
      });
  });

  // show phones
  $('.js-phone').click(function(){
    var $this = $(this)
    // $this.parent().siblings().filter('.hide-phone').show()
    // $this.hide()
    let url = $(this).data('url');
    $.ajax({
      url: url,
      type: 'GET',
      success: function(response) {
        if (response.length != 0) {
          $('#phoneModal').modal('show');
          $('#phoneBody').empty();
          var html = ''
          for (var i = 0; i < response.length; i++) {
            html += '<tr>'
            html += '<td>' + response[i]['fields']['phone'] + '</td>'
            html += '</tr>'
          }
          $('#phoneBody').append(html)
        } else {
          alert('No Phone');
        }
      },
      error: function(xhr) {
        console.log('Error');
      },
    })
  });
</script>


<hr>
<div>
<h4><b>Total:</b> {{ page_obj.paginator.count }} contato{{ page_obj.paginator.count|pluralize }}</h4>
</div>

{% include "pagination.html" %}

{% endblock content %}

myproject/core/templates/footer.html
<div id="footer">
  <div class="container">
    <p class="credit pull-left">Example by <a href="https://github.com/rg3915/">Régis da Silva</a> &copy; 2016 &middot; <a href="">download</a></p>
    <div class="socialfooter pull-center">
      <ul>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-skype"></i></a></li>
        <li><a href="#"><i class="fa fa-slack"></i></a></li>
      </ul>
    </div>
  </div>
</div>

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <h1>Bem vindo!</h1>
    <a href="{% url 'core:person_add' %}">
      <button id="new_customer" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span> Cadastre-se
      </button>
    </a>
  </div>
{% endblock content %}

myproject/core/templates/nav.html
<!-- Menu -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'core:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url 'core:person_list' %}"><span class="fa fa-users"></span> Lista de Contatos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}"><span class="fa fa-drupal"></span> Admin</a></li>
      </ul>
    </div>
  </div>
</div>

myproject/core/templates/pagination.html
<!-- pagination -->
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% endif %}
      {% for pg in page_obj.paginator.page_range %}
        {% if page_obj.number == pg %}
          <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
        {% else %}
          <li><a href="?page={{ pg }}">{{ pg }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>
<!-- https://www.technovelty.org/web/skipping-pages-with-djangocorepaginator.html -->